[DMZ]
eco-proxy ansible_host=10.10.1.10 ansible_user=marlene

[LAN]
eco-app  ansible_host=10.10.2.10 ansible_user=cynthia
eco-web  ansible_host=10.10.2.20 ansible_user=marlene
eco-db   ansible_host=10.10.2.30 ansible_user=cynthia

[MGT]
eco-sec  ansible_host=10.10.3.20 ansible_user=jovani

[IoT]
eco-mqtt ansible_host=10.10.4.10 ansible_user=jovani

[all:vars]
ansible_python_interpreter=/usr/bin/python3
