# Nginx - ECO-PROXY ECOTRACK
server {
    listen 443 ssl;
    ssl_protocols TLSv1.3;
    ssl_certificate /etc/ssl/ecotrack/certs/proxy.crt;
    ssl_certificate_key /etc/ssl/ecotrack/keys/proxy.key;
    modsecurity on;
    location / {
        proxy_pass http://10.10.2.10:3000;
    }
}
